SELECT
	p.title AS 'Title',
	REPLACE(p.title, ' ', '-') AS 'URLhandle',
	'' AS 'Description',
	'Exotic India' AS 'Vendor',
	'Home & Garden>Decor>Figurines' AS 'Product category',
	case
		when p.groupname = 'sculptures' then 'Brass Statue'
		when p.groupname = 'homeandliving' then 'home and living'
		else ''
	end AS 'Type',
	'' AS 'Tags',
	'TRUE' AS 'Published on online store',
	'active' AS 'Status',
	p.itemcode AS 'SKU',
	'' AS 'Barcode',
	'' AS 'Option1 name',
	'' AS 'Option1 value',
	'' AS 'Option2 name',
	'' AS 'Option2 value',
	'' AS 'Option3 name',
	'' AS 'Option3 value',
	psp.price_india + psp.price_india * psp.gst / 100 AS 'Price',
	'' AS 'Price / International',
	(psp.price_india + psp.price_india * psp.gst / 100)+ (psp.price_india + psp.price_india * psp.gst / 100)/ 4 AS 'Compare-at price',
	'' AS 'Compare-at price / International',
	'' AS 'Cost per item',
	'TRUE' AS 'Charge tax',
	'' AS 'Tax code',
	'' AS 'Unit price total measure',
	'' AS 'Unit price total measure unit',
	'' AS 'Unit price base measure',
	'' AS 'Unit price base measure unit',
	'' AS 'Inventory tracker',
	'50' AS 'Inventory quantity',
	'CONTINUE' AS 'Continue selling when out of stock',
	'' AS 'Weight value (grams)',
	'g' AS 'Weight unit for display',
	'TRUE' AS 'Requires shipping',
	'manual' AS 'Fulfillment service',
	CONCAT("https://cdn.exoticindia.com/images/products/original/", replace(REPLACE(lower(p.image), ".webp", ""), ".jpg", ""), CASE WHEN psp.color = "" THEN "" ELSE concat("-", REPLACE(lower(psp.color), " ", "")) END, ".jpg") AS 'Product image URL',
	'1' AS 'Image position',
	CONCAT("https://cdn.exoticindia.com/images/products/original/", replace(REPLACE(lower(p.image), ".webp", ""), ".jpg", ""), CASE WHEN psp.color = "" THEN "" ELSE concat("-", REPLACE(lower(psp.color), " ", "")) END, "_a01", ".jpg") AS 'Product image URL',
	'2' AS 'Image position',
	CONCAT("https://cdn.exoticindia.com/images/products/original/", replace(REPLACE(lower(p.image), ".webp", ""), ".jpg", ""), CASE WHEN psp.color = "" THEN "" ELSE concat("-", REPLACE(lower(psp.color), " ", "")) END,"_a02", ".jpg") AS 'Product image URL',
	'3' AS 'Image position',
	CONCAT("https://cdn.exoticindia.com/images/products/original/", replace(REPLACE(lower(p.image), ".webp", ""), ".jpg", ""), CASE WHEN psp.color = "" THEN "" ELSE concat("-", REPLACE(lower(psp.color), " ", "")) END,"_a03", ".jpg") AS 'Product image URL',
	'4' AS 'Image position',
	CONCAT("https://cdn.exoticindia.com/images/products/original/", replace(REPLACE(lower(p.image), ".webp", ""), ".jpg", ""), CASE WHEN psp.color = "" THEN "" ELSE concat("-", REPLACE(lower(psp.color), " ", "")) END,"_a04", ".jpg") AS 'Product image URL',
	'5' AS 'Image position',
	CONCAT("https://cdn.exoticindia.com/images/products/original/", replace(REPLACE(lower(p.image), ".webp", ""), ".jpg", ""), CASE WHEN psp.color = "" THEN "" ELSE concat("-", REPLACE(lower(psp.color), " ", "")) END,"_a05", ".jpg") AS 'Product image URL',
	'6' AS 'Image position',
	CONCAT("https://cdn.exoticindia.com/images/products/original/", replace(REPLACE(lower(p.image), ".webp", ""), ".jpg", ""), CASE WHEN psp.color = "" THEN "" ELSE concat("-", REPLACE(lower(psp.color), " ", "")) END,"_a06", ".jpg") AS 'Product image URL',
	'7' AS 'Image position',
	CONCAT("https://cdn.exoticindia.com/images/products/original/", replace(REPLACE(lower(p.image), ".webp", ""), ".jpg", ""), CASE WHEN psp.color = "" THEN "" ELSE concat("-", REPLACE(lower(psp.color), " ", "")) END,"_a07", ".jpg") AS 'Product image URL',
	'8' AS 'Image position',
	CONCAT("https://cdn.exoticindia.com/images/products/original/", replace(REPLACE(lower(p.image), ".webp", ""), ".jpg", ""), CASE WHEN psp.color = "" THEN "" ELSE concat("-", REPLACE(lower(psp.color), " ", "")) END,"_a08", ".jpg") AS 'Product image URL',
	'9' AS 'Image position',
	CONCAT("https://cdn.exoticindia.com/images/products/original/", replace(REPLACE(lower(p.image), ".webp", ""), ".jpg", ""), CASE WHEN psp.color = "" THEN "" ELSE concat("-", REPLACE(lower(psp.color), " ", "")) END,"_a09", ".jpg") AS 'Product image URL',
	'10' AS 'Image position',
	'' AS 'Image alt text',
	'' AS 'Variant image URL',
	'' AS 'Gift card',
	'' AS 'SEO title',
	'' AS 'SEO description',
	ROUND(CASE WHEN psp.length_unit IS NULL THEN psp.prod_length WHEN LOWER(REPLACE(psp.length_unit,' ','')) IN ('inch','in','inches') THEN psp.prod_length WHEN LOWER(REPLACE(psp.length_unit,' ','')) IN ('ft','feet','foot') THEN psp.prod_length*12 WHEN LOWER(REPLACE(psp.length_unit,' ','')) IN ('m','meter','metre') THEN psp.prod_length*39.3701 WHEN LOWER(REPLACE(psp.length_unit,' ',''))='cm' THEN psp.prod_length/2.54 WHEN LOWER(REPLACE(psp.length_unit,' ',''))='mm' THEN psp.prod_length/25.4 ELSE psp.prod_length END,2) AS 'Depth (product.metafields.custom.depth)',
	ROUND(CASE WHEN psp.length_unit IS NULL THEN psp.prod_height WHEN LOWER(REPLACE(psp.length_unit,' ','')) IN ('inch','in','inches') THEN psp.prod_height WHEN LOWER(REPLACE(psp.length_unit,' ','')) IN ('ft','feet','foot') THEN psp.prod_height*12 WHEN LOWER(REPLACE(psp.length_unit,' ','')) IN ('m','meter','metre') THEN psp.prod_height*39.3701 WHEN LOWER(REPLACE(psp.length_unit,' ',''))='cm' THEN psp.prod_height/2.54 WHEN LOWER(REPLACE(psp.length_unit,' ',''))='mm' THEN psp.prod_height/25.4 ELSE psp.prod_height END,2)  AS 'Height (product.metafields.custom.height)',
	ROUND(CASE WHEN psp.product_weight_unit IS NULL THEN psp.product_weight WHEN LOWER(REPLACE(psp.product_weight_unit,' ','')) IN ('kg','kgs','kilogram','kilograms') THEN psp.product_weight WHEN LOWER(REPLACE(psp.product_weight_unit,' ','')) IN ('g','gram','grams') THEN psp.product_weight/1000 WHEN LOWER(REPLACE(psp.product_weight_unit,' ','')) IN ('mg','milligram','milligrams') THEN psp.product_weight/1000000 WHEN LOWER(REPLACE(psp.product_weight_unit,' ','')) IN ('lb','lbs','pound','pounds') THEN psp.product_weight*0.453592 WHEN LOWER(REPLACE(psp.product_weight_unit,' ','')) IN ('oz','ounce','ounces') THEN psp.product_weight*0.0283495 WHEN LOWER(REPLACE(psp.product_weight_unit,' ','')) IN ('t','ton','tons','tonne') THEN psp.product_weight*1000 ELSE psp.product_weight END,3) AS 'Weight (product.metafields.custom.weight)',
	ROUND(CASE WHEN psp.length_unit IS NULL THEN psp.prod_width WHEN LOWER(REPLACE(psp.length_unit,' ','')) IN ('inch','in','inches') THEN psp.prod_width WHEN LOWER(REPLACE(psp.length_unit,' ','')) IN ('ft','feet','foot') THEN psp.prod_width*12 WHEN LOWER(REPLACE(psp.length_unit,' ','')) IN ('m','meter','metre') THEN psp.prod_width*39.3701 WHEN LOWER(REPLACE(psp.length_unit,' ',''))='cm' THEN psp.prod_width/2.54 WHEN LOWER(REPLACE(psp.length_unit,' ',''))='mm' THEN psp.prod_width/25.4 ELSE psp.prod_width END,2) AS 'Width (product.metafields.custom.width)',
	'' AS 'EI Category (product.metafields.custom.eicategory)',
	'Home & Garden>Decor>Figurines' AS 'Google Shopping / Google product category',
	'' AS 'Google Shopping / Gender',
	'' AS 'Google Shopping / Age group',
	'' AS 'Google Shopping / MPN',
	'' AS 'Google Shopping / AdWords Grouping',
	'' AS 'Google Shopping / AdWords labels',
	'NEW' AS 'Google Shopping / Condition',
	'' AS 'Google Shopping / Custom product',
	'' AS 'Google Shopping / Custom label 0',
	'' AS 'Google Shopping / Custom label 1',
	'' AS 'Google Shopping / Custom label 2',
	'' AS 'Google Shopping / Custom label 3',
	'' AS 'Google Shopping / Custom label 4'
from
	products p
left join products_stock_prices psp on
	psp.itemcode = p.itemcode
where
	p.groupname in ('sculptures', 'homeandliving')
and psp.stock_date_added >= 